### PR TITLE
Switch from M2Crypto to cryptography for delegate proxy activation

### PR DESCRIPTION
**Pull request by aaschaer**
Hopefully this will make our dependencies less painful.

This should address #311 since cryptography uses one function to parse all private key types, and I switched to using a regex to parse the PEM files to make use of this. Haven't tested yet, and don't know what would happen if someone gave us a non RSA private key.

Includes some security updates, the old code was using SHA1, and X.509 v2 (yet still managed to add extensions somehow?) new code is using SHA256 and X.509 v3

I added a sentence about `pip install globus_cli[delegate-proxy]` to the activation adoc, do we want to add this to our install page as well?

### CODE REVIEW

**Comment by aaschaer** [comment]
Looks like we still have some travis pypy issues.

Cryptography is only compatible with pypy >= 2.6, and travis's  default versions are 2.5 for pypy and 2.4 for pypy3. Travis does allow specifying pypy versions, but doing so requires sudo, and even after activating that my builds were breaking on the pypy install.

I did manage to get travis half-working by only turning on sudo and not specifying a pypy version, but it seems only pypy updated automatically, where as pypy3 was still stuck at 2.4.

I decided the simplest solution was to keep skipping cryptography on pypy runs, but if someone who's better at travis than me wants to get an updated version working, delegate proxy *should* work with pypy >= 2.6 now.

**Comment by jaswilli** [comment]
Fully on board with just continuing to skip pypy until we can reasonably get current releases on travis.

**Comment by sirosen** [comment]
This all looks good to me, barring one small typo ("Gloubus" in an adoc file).

I'm going to test it out on my own machine and see if I can get it to work before merging.

**Comment by aaschaer** [comment]
Fixed and squahsed the typo (And added Globus to my spell-check dictionary)

**Comment by sirosen** [comment]
Works for me, clearly works for everyone.

Thanks for fixing up the typo. ( :laughing: about you adding it to your dictionary. I've come to ignore spellcheck on anything technical. My spellchecker doesn't even recognize "spellcheck" as a word!)

Like Jason, I'm cool with skipping crypto tests on pypy. If we can fix it in the future, that would be great, but no harm leaving it as-is.

**Pull request merged**
