### PR TITLE
Check identity ID with UUID, not regex

### LINKED ISSUE #484: Check Identity ID vs Identity Name by checking for UUID, not regex
In [the SDK port of IdentityMap](https://github.com/globus/globus-sdk-python/pull/367), this came up as a potential issue.

Here's where the regex matching comes from:
https://github.com/globus/globus-cli/blob/50c7b4ac669b2f9f081ce9d696d602f57e3212ed/globus_cli/services/auth.py#L13

It's not certain that this is an issue -- certainly, nobody has complained thusfar -- but we should look things over and see if the same improvement can be made here.

### PR DESCRIPTION
**Pull request by sirosen**
resolves #484

### CODE REVIEW

**Comment by jaswilli** [comment]
I'm having a hard time connecting the dots. Is it okay to only check for UUIDs because the IdentityMap is resolving usernames to IDs prior to this check happening?

**Comment by sirosen** [comment]
This is for get-identities ; I don't think any other commands use it. An id outputs username, and a username outputs id, so we need to accept both and detect which is which.
We've been doing it with a regex. This just switches to try-except handling around uuid parsing instead.

**Comment by sirosen** [comment]
I just noticed this again and thought "didn't I do something else like this?" And I did! I'm pretty sure this is redundant with #509 . This could go in first -- they aren't mutually exclusive -- but I think #509 is the better overall approach to parsing username-or-id parameters.

**Comment by jaswilli** [comment]
Yeah, I've got it now. I remembered that's what this was concerned with but the way the diff read had me confused.

I'll look at the other change before this one. I didn't want to merge that one for 1.x/2.x but I'm sure it's fine now.

**Comment by sirosen** [comment]
I'm moving this forward since it's not fully redundant with #509 .

**Pull request merged**
