### PR TITLE
Update installation instructions: always use venv

### PR DESCRIPTION
**Pull request by sirosen**
These new install instructions _should_ let us neatly sidestep the issues with global installs without putting too much burden on the user.

Recommendation for review: actually pull down this branch and open `file:///.../globus-cli/docs/index.html` to see how it "looks and feels".

### CODE REVIEW

**Comment by jaswilli** [comment]
I tested this on OS X and it works fine. I also tested on Windows (10) and it works, except the instructions need to be changed for updating the path, obviously.

Also, I think if we go this route we're going to need to provide "Updating" and "Uninstalling" documentation.

**Comment by sirosen** [comment]
@jaswilli If the below instructions are acceptable, let's add them. If they are not, can we punt on this as a problem for another day?

```rst
Update
------
To update your version of the CLI to the latest:

.. code-block:: bash

    source $HOME/.globus-cli-virtualenv/bin/activate
    pip install -U globus-cli
    deactivate

Uninstall
---------

To remove the CLI:

.. code-block:: bash

    rm -r $HOME/.globus-cli-virtualenv

You should also edit your ``$HOME/.bashrc`` and remove the line that reads ``export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"``.
```

**Comment by jaswilli** [comment]
Yes, those look reasonable (keeping in mind that they need to be amended for Windows).

**Comment by sirosen** [comment]
I think we can safely say that this closes #26 and globus/globus-sdk-python#51

**Comment by corpulentcoffee** [comment]
This looks very much improved to me.

Very stupid quibble: can we use either `~` or `$HOME` consistently, instead of switching between the two? (As for which one, I think people are used to seeing `~` in terminal snippets and are used to typing it in their terminal. I don't know anyone who types out `$HOME` in interactive commands.)

**Comment by sirosen** [comment]
I'd like to use `$HOME` everywhere, but `~` sometimes slips in when I'm not paying attention.
I agree that `~` is more idiomatic / "comfortable", but it's not quite as safe.

The reasoning is simply that shells respect `"~"` by not expanding, so, if someone copies a dirname and quotes it, bad times ensue.
I'll amend to have no `~`s.

**Comment by corpulentcoffee** [comment]
Yes, that is true.

**Comment by jaswilli** [comment]
Also, FWIW, `$HOME` works in Powershell but `~` does not.

**Comment by corpulentcoffee** [comment]
That's another good reason.

**Comment by sirosen** [comment]
I also realized I needed to quote `$HOME` to avoid the possibility of word-splitting if someone's home has spaces in it. That actually matters, on account of the `rm -r` command offered up.

**Pull request merged**
